__metadata:
  exclude_from_tar: true

deployment:
  tasks:
    - echo "🛠️ Installing dependencies..."
    - npm install
    - echo "🔨 Building static assets..."
    - npm run build
    - echo "🚚 Copying build to public_html..."
    - rm -rf $HOME/public_html/smmowcub.org/*
    - cp -R dist/* $HOME/public_html/smmowcub.org/
    - echo "📋 Copying .htaccess file..."
    - cp .htaccess $HOME/public_html/smmowcub.org/
    - echo "🔧 Setting proper permissions..."
    - chmod 644 $HOME/public_html/smmowcub.org/.htaccess
    - echo "✅ Deployment complete!"